version: 2
jobs:
  build:
    docker:
      - image: gcr.io/eaglesakura-container/github/army-knife:1.0.1
        auth:
            username: _json_key
            password: $SERVICE_ACCOUNT_JSON
        environment:
          _JAVA_OPTIONS: -Dfile.encoding=UTF-8
          GRADLE_OPTS: "-Xmx2g"
          CACHE_VERSION: "1.0"
          TZ: Asia/Tokyo
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
      - run:
          name: setup
          command: fastlane ci setup
      - run:
          name: test
          command: fastlane android test
      - run:
          name: assemble
          command: fastlane android assemble
      - run:
          name: deploy
          command: fastlane ci deploy
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/project/.configs
          key: gradle-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
      - store_artifacts:
          path: artifacts
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
# EOF
