version: 2
jobs:
  build:
    docker:
      - image: gcr.io/eaglesakura-container/github/army-knife:1.0.0
        auth:
            username: _json_key
            password: $SERVICE_ACCOUNT_JSON
        environment:
          CIRCLE_ARTIFACTS: /tmp/artifacts
          _JAVA_OPTIONS: -Dfile.encoding=UTF-8
          GRADLE_OPTS: "-Xmx3g"
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}-{{ checksum "army-knife/build.gradle" }}
      - run:
          name: setup
          command: |
            chmod +x -R .circleci/scripts/
            .circleci/scripts/setup.sh
      - run:
          name: test
          command: .circleci/scripts/test.sh
      - run:
          name: assemble
          command: .circleci/scripts/assemble.sh
      - run:
          name: deploy
          command: .circleci/scripts/deploy.sh
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
            - ~/project/.configs
          key: gradle-{{ checksum ".circleci/config.yml" }}-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}-{{ checksum "army-knife/build.gradle" }}
      - store_artifacts:
          path: /tmp/artifacts
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
# EOF
