# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# good sample! https://qiita.com/matsuokah/items/06ff8b50c0e2be828786

$projects=[
    "army-knife",
    "army-knife-android-junit4",
    "army-knife-camera",
    "army-knife-gms",
    "army-knife-junit",
    "army-knife-persistence",
    "army-knife-reactivex",
    "army-knife-timber",
    "army-knife-view-adapters",
    "firearm",
    "firearm-channel",
    "firearm-di",
    "firearm-event",
    "firearm-material-resources",
    "firearm-persistence",
    "kerberus",
    "oneshotlivedata"
    ]
$docker_image = "gcr.io/eaglesakura-container/github/army-knife:1.0.2"
$build_number=ENV["CIRCLE_BUILD_NUM"]
$build_sha1=ENV["CIRCLE_SHA1"]

import "./project.rb"
import "./android.rb"
